- name: Playbook demo for assert module
  hosts: dev_servers
  tasks:
   - name: Check Host System Status
     ansible.builtin.ping:
     async: 1
     poll: 0
     register: status
    
   - name: Wait for asynchronous job to end
     ansible.builtin.async_status:
      jid: '{{ status.ansible_job_id }}'
     register: job_result
     until: job_result.finished
     retries: 100
     delay: 10
     
    
