- name : "Execute Cron Jobs"
  hosts: server_01
  tasks:
   - name : "Write tet to hello.txt file every minute"
     ansible.builtin.cron:
      name : "Write message to hello.txt"
      minute: "*"
      hour: "*"
      day : "*"
      month: "*"
      weekday: "*"
      job: 'echo "Hello to My World - $(date)"  >> hello.txt'
   - name : "Remove Cron Job"
     ansible.builtin.cron:
      name: "Write message to hello.txt"
      state: absent
      
       
