Vagrant.configure("2") do |config| 
 vm_names = ["M1","M2"]
 vm_names.each do |name|
  config.vm.define name do |vm|
    vm.vm.box = "hashicorp/bionic64"
    vm.vm.network "public_network"
    vm.vm.provision "shell", path: "script.sh"
  end
 end
end
